### ISSUE TITLE
add libremidi to vcpkg?

### ISSUE THREAD

**Issue by ericfont** [jcelerier/libremidi#50] opened 2021-10-08 04:21 UTC
[vcpkg](https://github.com/microsoft/vcpkg) seems to be a good way for including C/C++ libraries in a cross-platform manner and have them downloadable and work well with github-ci and such.  RtMidi and PortMidi are in vcpkg:

https://github.com/microsoft/vcpkg/tree/master/ports/rtmidi
https://github.com/microsoft/vcpkg/tree/master/ports/portmidi

I notice you already have support for conan according to https://github.com/jcelerier/libremidi/issues/45, but I think it would be good to also add to vcpkg cause then more users could easily include if they are using vcpkg for library management.

**Comment by ericfont** [comment] 2021-10-09 17:57
https://github.com/Microsoft/vcpkg/blob/master/CONTRIBUTING.md#new-package-guidelines

**Comment by ericfont** [comment] 2021-10-09 18:58
I added a "New port request" at https://github.com/microsoft/vcpkg/issues/20623

**Comment by jcelerier** [comment] 2023-07-27 23:13
the cmake part has been done for quite a while

**Comment by marinedalek** [comment] 2023-09-19 02:44
I've created a draft pull request for vcpkg implementing the libremidi library. Currently the automated testing is failing because the UWP builds fail. It seems like the UWP build is trying to link against WinMM... but there may be something I'm missing! Here is the pull request on the vcpkg repo: https://github.com/microsoft/vcpkg/pull/33848

Also, if anyone wants to test the library in vcpkg, my branch is here: https://github.com/marinedalek/vcpkg/tree/libremidi
Clone it using 
```git clone https://github.com/marinedalek/vcpkg.git --branch libremidi``` and run 
```bootstrap-vcpkg.bat``` to download the vcpkg binary.

There are further instructions here: https://learn.microsoft.com/en-us/vcpkg/examples/manifest-mode-cmake
or to build just the UWP version, you can run ```vcpkg install libremidi:x64-uwp```

**Comment by jcelerier** [comment] 2023-09-24 18:02
heya, I'm going through all the steps - it seems to work on already most of the OSes, super nice and thanks for doing this!

### First build error

https://dev.azure.com/vcpkg/public/_build/results?buildId=94328&view=logs&j=878666d5-db33-5b27-9e7d-b0c7ee352005&t=3980505e-92f5-53ef-75a8-4f2e70b97516

```
##[error]Found the following errors:
##[error]versions/l-/libremidi.json(2,): error : while parsing versions for libremidi from version/l-/libremidi.json
4.0 is declared with 596c1313e051acf0d6af025900facc7174c8d12b, but the local port has a different SHA b11db5e2edfeb6789c91b45c19f2b9fb3f60a35e.
```

I guess some SHA has to be updated somewhere.. weird that it does not cause any issue on the other builds though, maybe a spurious failure.

### Second and third error 

https://dev.azure.com/vcpkg/public/_build/results?buildId=94328&view=logs&j=afe306fb-88a0-5d5e-2934-71aa01507316&t=5029ab74-fefd-5c62-0657-5855530a064d

https://dev.azure.com/vcpkg/public/_build/results?buildId=94328&view=logs&j=f3185963-cf64-542d-738a-b43a7110d124&t=2c19ce80-94f8-552d-2342-a0796f515613

```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j33
    Working Directory: D:/buildtrees/libremidi/x64-uwp-dbg
    See logs for more information:
      D:\buildtrees\libremidi\install-x64-uwp-dbg-out.log

Call Stack (most recent call first):
  D:/installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  D:/installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/libremidi/portfile.cmake:13 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

```

to check this I'd really need to see the `D:\buildtrees\libremidi\install-x64-uwp-dbg-out.log` log file... error can be anywhere. gonna try a build against UWP platform locally to see...

**Comment by jcelerier** [comment] 2023-09-24 18:21
okay, I could reproduce an error locally.. it seems that just setting LIBREMIDI_NO_WINMM in the offending cases is enough. i'll add acheck for if we're targeting windows store.

**Comment by jcelerier** [comment] 2023-09-24 18:29
if you can try with git master..

**Comment by marinedalek** [comment] 2023-09-24 19:46
Hi, thanks for looking at this! The first build error is just an internal check for something that needs to be set once all modifications to the port are complete - I'll fix that just before marking the pull request as ready.

Sounds like you found the source of the error I was seeing, so I'll test building from head later after I finish work. 

Thanks again!

**Comment by jcelerier** [comment] 2023-09-24 23:35
I tagged a new version with the fixes if it makes it easier

**Comment by marinedalek** [comment] 2023-09-25 02:02
That's great! I've updated the port to point to the new tag, and all checks now pass. I've marked the pull request as ready and requested a re-review with the new changes, so hopefully (assuming there are no further review comments) it should be accepted and merged soon :)

**Comment by jcelerier** [comment] 2023-09-26 01:30
super thank you so much!

**Comment by jcelerier** [comment] 2023-09-26 18:31
seems to have been merged to vcpkg, yay!

**Closed by jcelerier** 2023-09-26 18:31 UTC
Labels: enhancement, help wanted

**Comment by totalgee** [comment] 2024-12-27 13:51
I'm trying to use libremidi via vcpkg on Linux (Arch), and I get a build error, which comes from `backends/pipewire/midi_out.hpp`, which is trying to include `readerwriterqueue.h` -- this file is not found.

https://github.com/celtera/libremidi/blob/b18a2fc38a020e0cc4b174c257de182a4328da58/include/libremidi/backends/pipewire/midi_out.hpp#L6

Is there a missing third-party dependency or something, so that libremidi can build under Pipewire and vcpkg?

**Comment by jcelerier** [comment] 2024-12-27 14:11
ah that's right, the dependency looks like it has not been added to vcpkg

**Comment by totalgee** [comment] 2024-12-27 14:22
Added a comment here; I'm not experienced with vcpkg stuff so I don't know if that's the correct way to fix it:

https://github.com/microsoft/vcpkg/issues/20623

**Comment by jcelerier** [comment] 2025-01-30 17:02
hmm it includes it in libremidi.pipewire.cmake:

```cmake
  target_link_libraries(libremidi
    ${_public}
      ${CMAKE_DL_LIBS}
      $<BUILD_INTERFACE:readerwriterqueue>
  )
```

**Comment by totalgee** [comment] 2025-01-30 17:34
Thanks, I do see that `libremidi: using PipeWire` message logged in the CMake logs (also `using ALSA`, `ALSA RawMIDI: 1`, `ALSA UMP: 1`, `udev support`).

In the CMake build, I have the following defines: `-DLIBREMIDI_ALSA -DLIBREMIDI_EXPORTS -DLIBREMIDI_HAS_UDEV -DLIBREMIDI_NO_BOOST -DLIBREMIDI_PIPEWIRE`.

Hmm, I do see a message just after that, which is probably the issue (though I don't know how to fix it)...

```
CMake Warning at /usr/share/cmake/Modules/FetchContent.cmake:2111 (message):
  FETCHCONTENT_FULLY_DISCONNECTED is set to true, which requires the source
  directory for dependency readerwriterqueue to already be populated.  This
  generally means it must not be set to true the first time CMake is run in a
  build directory.  The following source directory should already be
  populated, but it doesn't exist:

    /home/[...]/vcpkg/buildtrees/libremidi/x64-linux-dbg/_deps/readerwriterqueue-src

  Policy CMP0170 controls enforcement of this requirement.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FetchContent.cmake:2384 (__FetchContent_Populate)
  cmake/libremidi.deps.cmake:37 (FetchContent_MakeAvailable)
  CMakeLists.txt:50 (include)
```

Any idea how to fix this? I've tried deleting various vcpkg caches, and other CMake data directories, but always with the same effect. Thanks!

**Comment by jcelerier** [comment] 2025-01-30 17:51
I don't use enough vcpkg to be able to tell, sorry :( but this does not look like something that should be enabled, maybe it's the distro setting it ? from the CMake docs it looks like you should actually get a hard error here even before the build starts:

https://cmake.org/cmake/help/latest/policy/CMP0170.html

**Comment by totalgee** [comment] 2025-01-30 18:13
I don't know enough about it, either. Maybe the issue is the `if` clause `AND NOT TARGET readerwriterqueue`, somehow it already exists as a target, so it's skipping `FetchContent_Declare` for readerwriterqueue...? I don't know how to continue debugging this.

**Comment by jcelerier** [comment] 2025-01-30 18:25
if `readerwriterqueue` exists as a target then 

  target_link_libraries(libremidi
    ${_public}
      ${CMAKE_DL_LIBS}
      $<BUILD_INTERFACE:readerwriterqueue>
  )

would work and add the correct include paths. the "AND NOT" is made basically for the case when libremidi is included as a subdirectory of another software which may also use readerwriterqueue, to avoid ODR issues and multiple versions of the same library in the same build trree

**Comment by jcelerier** [comment] 2025-01-30 18:52
since I'm on archlinux I could try on my side.. which steps did you do to get to this state ?

**Comment by totalgee** [comment] 2025-01-31 08:48
BTW, I checked on the other Linux machine where it worked (once the dependency for `readerwriterqueue` was added to the vcpkg port). I do actually see the same CMP0170 policy error message during CMake config time (twice, actually), about the `readerwriterqueue-src` folder not being found, even if it later builds properly.

However, on that machine (which is running Pop! OS, a derivative of Ubuntu, and Gnome window manager I believe), the defines for PIPEWIRE (in the CMakeCache) are:
```
config-x64-linux-rel-CMakeCache.txt.log:LIBREMIDI_NO_PIPEWIRE:BOOL=OFF
config-x64-linux-rel-CMakeCache.txt.log:PIPEWIRE_PATH:PATH=PIPEWIRE_PATH-NOTFOUND
config-x64-linux-rel-CMakeCache.txt.log:PIPEWIRE_SPA_PATH:PATH=PIPEWIRE_SPA_PATH-NOTFOUND
```

When compiling midi_out.cpp, it uses these flags (not compiling the PipeWire backend, it seems):
```
[8/13] /usr/bin/c++ -DLIBREMIDI_ALSA -DLIBREMIDI_EXPORTS -DLIBREMIDI_HAS_UDEV -DLIBREMIDI_NO_BOOST -I/home/[...]/vcpkg/buildtrees/libremidi/x64-linux-dbg -I/home/[...]/vcpkg/buildtrees/libremidi/src/v4.5.0-c7b9464d29.clean -I/home/[...]/vcpkg/buildtrees/libremidi/src/v4.5.0-c7b9464d29.clean/include -I/home/[...]/[...]/build/vcpkg_installed/x64-linux/include -fPIC -g -std=gnu++20 -fPIC -Wall -Wextra -MD -MT CMakeFiles/libremidi.dir/include/libremidi/midi_out.cpp.o -MF CMakeFiles/libremidi.dir/include/libremidi/midi_out.cpp.o.d -o CMakeFiles/libremidi.dir/include/libremidi/midi_out.cpp.o -c /home/[...]/vcpkg/buildtrees/libremidi/src/v4.5.0-c7b9464d29.clean/include/libremidi/midi_out.cpp
```

**Comment by totalgee** [comment] 2025-01-31 11:49
On the machine where it fails, I get this:

```
config-x64-linux-dbg-CMakeCache.txt.log:LIBREMIDI_NO_PIPEWIRE:BOOL=OFF
config-x64-linux-dbg-CMakeCache.txt.log:PIPEWIRE_PATH:PATH=/usr/include/pipewire-0.3
config-x64-linux-dbg-CMakeCache.txt.log:PIPEWIRE_SPA_PATH:PATH=/usr/include/spa-0.2
```

And when compiling midi_out.cpp, it uses these flags, and has these errors:
```
[5/13] /usr/bin/g++ -DLIBREMIDI_ALSA -DLIBREMIDI_EXPORTS -DLIBREMIDI_HAS_UDEV -DLIBREMIDI_NO_BOOST -DLIBREMIDI_PIPEWIRE -I/home/[...]/vcpkg/buildtrees/libremidi/x64-linux-dbg -I/home/[...]/vcpkg/buildtrees/libremidi/src/v4.5.0-c7b9464d29.clean -I/home/[...]/vcpkg/buildtrees/libremidi/src/v4.5.0-c7b9464d29.clean/include -I/home/[...]/[...]/vcpkg_installed/x64-linux/include -isystem /usr/include/pipewire-0.3 -isystem /usr/include/spa-0.2 -fPIC -g -std=gnu++20 -fPIC -Wall -Wextra -MD -MT CMakeFiles/libremidi.dir/include/libremidi/libremidi.cpp.o -MF CMakeFiles/libremidi.dir/include/libremidi/libremidi.cpp.o.d -o CMakeFiles/libremidi.dir/include/libremidi/libremidi.cpp.o -c /home/[...]/vcpkg/buildtrees/libremidi/src/v4.5.0-c7b9464d29.clean/include/libremidi/libremidi.cpp
FAILED: CMakeFiles/libremidi.dir/include/libremidi/libremidi.cpp.o 
In file included from /home/[...]/vcpkg/buildtrees/libremidi/src/v4.5.0-c7b9464d29.clean/include/libremidi/backends/pipewire.hpp:7,
                 from /home/[...]/vcpkg/buildtrees/libremidi/src/v4.5.0-c7b9464d29.clean/include/libremidi/backends.hpp:33,
                 from /home/[...]/vcpkg/buildtrees/libremidi/src/v4.5.0-c7b9464d29.clean/include/libremidi/libremidi.cpp:5:
/home/[...]/vcpkg/buildtrees/libremidi/src/v4.5.0-c7b9464d29.clean/include/libremidi/backends/pipewire/midi_out.hpp:6:10: fatal error: readerwriterqueue.h: No such file or directory
    6 | #include <readerwriterqueue.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

So the difference, compared to the other machine's compile line, is the addition of:
`-DLIBREMIDI_PIPEWIRE -isystem /usr/include/pipewire-0.3 -isystem /usr/include/spa-0.2`, but nothing for the include path of readerwriterqueue...

**Comment by totalgee** [comment] 2025-01-31 12:00
Also, in your documentation, you say for ArchLinux, you need `alsa-lib`, `jack2`, `libpipewire` and `systemd-libs`. I don't have `jack2`, because if I try to install this list of things, there is a conflict and it says (not sure if it could be related to my problem):

```
Warning: systemd-libs-256.9-1 is up to date -- skipping
Warning: libpipewire-1:1.2.7-1 is up to date -- skipping
Warning: alsa-lib-1.2.13-1 is up to date -- skipping
Resolving dependencies...
Checking inter-conflicts...

To install (1):
  jack2          1.9.22-1                           extra  482,9 kB
To remove (1):
  pipewire-jack  1:1.2.7-1  (Conflicts With: jack)  extra
```

**Comment by totalgee** [comment] 2025-01-31 12:27
I tried building the project on its own, cloned from Git, rather than via vcpkg. I used the exact build line shown in your instructions web page, and it built fine with the examples. It was using PipeWire, but it compiled perfectly...

Also, it did create a `build/_deps/readerwriterqueue-src/readerwriterqueue.h`...

Maybe the problem with vcpkg is (now that it has the dependency), it is not fetching the readerwriterqueue content, and somehow it's also not pointing to it (e.g. with an `-I` or `-isystem` include directive).

**Comment by jcelerier** [comment] 2025-01-31 20:11
ah great, thanks for cornering the issue !

it seems that for archlinux this is a recent packaging change...

**Comment by totalgee** [comment] 2025-01-31 23:27
Do you think the information I found might help you solve the vcpkg issue when using PipeWire? e.g. is there a way in your CMake files to detect this combination and be sure the vcpkg dependency include path for readerwriterqueue gets added? Or else to have the Fetch thing work, as it seems to when building "normally" with CMake and not under vcpkg? Thanks again, and sorry to keep hassling you!

**Comment by totalgee** [comment] 2025-02-04 10:51
Could it be that in this file, you need to add something like:

`$<BUILD_INTERFACE:readerwriterqueue>` also to the `target_include_directories`?

https://github.com/celtera/libremidi/blob/84bfabcff217ef540b20a83052715cd41db8d953/cmake/libremidi.pipewire.cmake#L34-L43

**Comment by totalgee** [comment] 2025-02-04 11:07
⚠ Aha, I think it's simply that the vcpkg version of libremidi that it's pulling for port 4.5.0#1 **doesn't** have your fix ba6732f0. The code that gets pulled by vcpkg when I try to build my project with vcpkg (the dependency specified is 4.5.0#1) does not have that commit in it, or even any recent ones. Instead, it seems to correspond to 4.5.0 from _March 3, 2024_...!

**Comment by totalgee** [comment] 2025-02-04 11:28
I don't know much about vcpkg, but I think the problem is in the `portfile.cmake`, which uses this:


`vcpkg_from_github(`
`    OUT_SOURCE_PATH SOURCE_PATH`
`    REPO jcelerier/libremidi`
`   `[`REF "v${VERSION}"`](https://github.com/microsoft/vcpkg/blob/bea476a80218a581bcb5318595849520217c825e/ports/libremidi/portfile.cmake#L4)
`    SHA512 4ba9d06a171dc29c393d5...`
`    HEAD_REF master`
`)`

Here it refers to the version, which is 4.5.0, and that's a tag dated from March last year... I think it should refer to a more recent commit SHA hash (or maybe you could make a tag and update the version to 4.5.1?).

**Comment by jcelerier** [comment] 2025-02-04 14:47
Okay, if that's the answer then I will try to tag a stable v5 soon

**Comment by totalgee** [comment] 2025-02-28 15:04
Not to be a hassle, but any word on this? 🤞 Thanks!

**Comment by jcelerier** [comment] 2025-03-01 17:24
hello ! I'm waiting for more advance on the new WinMidi SDK which still has occasional breaking changes :/ haven't tried the last one released yesterday: https://github.com/microsoft/MIDI/releases/tag/customer-preview-2 - will do asap

**Comment by totalgee** [comment] 2025-03-12 20:35
That's great, thanks! Do you know what's needed to update on the vcpkg side?

**Comment by jcelerier** [comment] 2025-03-12 20:52
It's mainly updating the portfile I think ? https://learn.microsoft.com/en-us/vcpkg/produce/update-package-version?pivots=shell-powershell

**Comment by totalgee** [comment] 2025-03-31 12:46
I thought I'd give it a try updating the portfile to 5.0.2, but I can't because there is no release/zip with that version. So I tried 5.0.1, but vcpkg install failed to build due to the Windows issue I think you fixed in 5.0.2:

```
   Creating library libremidi.lib and object libremidi.exp
midi_in.cpp.obj : error LNK2019: unresolved external symbol WINRT_IMPL_RoGetActivationFactory referenced in function "struct winrt::hresult __cdecl winrt::impl::get_runtime_activation_factory_impl<0>(struct winrt::param::hstring const &,struct winrt::guid const &,void * *)" (??$get_runtime_activation_factory_impl@$0A@@impl@winrt@@YA?AUhresult@1@AEBUhstring@param@1@AEBUguid@1@PEAPEAX@Z)
midi_out.cpp.obj : error LNK2001: unresolved external symbol WINRT_IMPL_RoGetActivationFactory
observer.cpp.obj : error LNK2001: unresolved external symbol WINRT_IMPL_RoGetActivationFactory
midi_in.cpp.obj : error LNK2019: unresolved external symbol WINRT_IMPL_RoOriginateLanguageException referenced in function "private: void __cdecl winrt::hresult_error::originate(struct winrt::hresult,void *,struct std::source_location const &)" (?originate@hresult_error@winrt@@AEAAXUhresult@2@PEAXAEBUsource_location@std@@@Z)
midi_out.cpp.obj : error LNK2001: unresolved external symbol WINRT_IMPL_RoOriginateLanguageException
observer.cpp.obj : error LNK2001: unresolved external symbol WINRT_IMPL_RoOriginateLanguageException
libremidi.dll : fatal error LNK1120: 2 unresolved externals
ninja: build stopped: subcommand failed.
```

Can you please make a 5.0.2 release, so I can try to publish it in vcpkg? Thanks!

**Comment by totalgee** [comment] 2025-03-31 12:49
(in the meantime, I'll try with v5.0.0)

**Comment by jcelerier** [comment] 2025-03-31 13:43
heya! vcpkg got updated to 5.2.0 normally, can you try this one?

**Comment by totalgee** [comment] 2025-03-31 14:24
Thanks, but what do you mean it got updated "normally"? The vcpkg versions still only show 4.5.0#1 as the latest, which is why I was planning to add 5.2.0 version to the port.

https://vcpkg.io/en/package/libremidi

**Comment by totalgee** [comment] 2025-03-31 15:21
Ah, now that makes sense. Thanks, hopefully they'll merge it soon.
